  ----------------------------------------------------------------------
  Python 3.8.10 (default, May 26 2023, 14:05:08)
  [GCC 9.4.0] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  -----------------------------------------------------------------------

  >>> add_integer = __import__('0-add_integer').add_integer
  -----------------------------------------------------------------------
  output using integers
  -----------------------------------------------------------------------
  >>> add_integer(2, 1)
  2
  >>> add_integer(100, 100)
  200
  >>> add_integer(1000, 1000)
  2000
  >>> add_integer(0, 1000)
  1000
  >>> add_integer(1, -1)
  0
  >>> add_integer(-1, -1)
  -2
  >>> add_integer(-1, -1.1)
  -2
  >>> add_integer(-1.1, -1.1)
  -2
  ------------------------------------------------------------------------
  output using no arguments
  -----------------------------------------------------------------------
  >>> add_integer()
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  TypeError: add_integer() missing 1 required positional argument: 'a'
  -----------------------------------------------------------------------
  output using one argument
  -----------------------------------------------------------------------
  >>> add_integer(1)
  99
  >>> add_integer(1, )
  99
  ------------------------------------------------------------------------
  output using None as argument
  ------------------------------------------------------------------------
  >>> add_integer(None)
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/kevinkoech357/Desktop/alx-higher_level_programming/0x07-python-test_driven_development/add_integer.py", line 27, in add_integer
      raise TypeError("a must be an integer")
  TypeError: a must be an integer
  -------------------------------------------------------------------------
  output using chars as argument
  -------------------------------------------------------------------------
  >>> add_integer('a', 'b')
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/kevinkoech357/Desktop/alx-higher_level_programming/0x07-python-test_driven_development/add_integer.py", line 27, in add_integer
      raise TypeError("a must be an integer")
  TypeError: a must be an integer
  >>> add_integer('a', )
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/kevinkoech357/Desktop/alx-higher_level_programming/0x07-python-test_driven_development/add_integer.py", line 27, in add_integer
      raise TypeError("a must be an integer")
  TypeError: a must be an integer
  >>> add_integer('b')
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  File "/home/kevinkoech357/Desktop/alx-higher_level_programming/0x07-python-test_driven_development/add_integer.py", line 27, in add_integer
    raise TypeError("a must be an integer")
  TypeError: a must be an integer
  >>> add_integer('a', 8)
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/kevinkoech357/Desktop/alx-higher_level_programming/0x07-python-test_driven_development/add_integer.py", line 27, in add_integer
      raise TypeError("a must be an integer")
  TypeError: a must be an integer
  >>>

